# Generated by Django 5.2 on 2025-08-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_adminphonenumber_alter_otpverification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount_tendered',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
