# Generated by Django 5.2 on 2025-08-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_create_user_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='minimum_stock_level',
            field=models.IntegerField(default=1),
        ),
    ]
